name: CI (Linux)

on: [push, pull_request]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check

      - name: check build
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: check
          args: --all --bins --examples --tests

      - name: tests
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          toolchain: nightly
          command: test
          args: --all --no-fail-fast -- --nocapture

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt

      - name: doc
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          toolchain: nightly
          command: doc
          args: --all --no-deps

  # publish:
  #   name: Publish Package
  #   needs: build_and_test
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install latest nightly
  #       uses: actions-rs/toolchain@v1
  #       with:
  #           toolchain: nightly
  #           override: true
  #           components: rustfmt

  #     - name: login
  #       env:
  #         SUPER_SECRET: ${{ secrets.CARGO_TOKEN }}
  #       run: cargo login "$SUPER_SECRET"
  #       shell: bash

  #     - name: publish
  #       uses: actions-rs/cargo@v1
  #       with:
  #         toolchain: nightly
  #         command: publish